### ISSUE TITLE
create action(s) for packages

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#2]
These actually *should* be separate actions, because

1. they should run on (some yet to be chosen) vanilla image (*not* byod)
2. they should first parse and download the `DESCRIPTION`. We don't want people to have to specify the dependencies in the `DESCRIPTION` *and* their byod in this case. This (the parsing) may need some amount of bashing.

**Comment by maxheld83** [comment]
this issue is too big and will need to be broken down into smaller parts.

**Comment by maxheld83** [comment]
Now, let's break this down into smaller pieces, sorted roughly by kind and (loosely) order of execution:

### Provisioning (for lack of a better term)

- [ ] choose an appropriate Docker image, or let the user provide one. #106


### CI (narrowly defined)

- [ ] `devtools::build()`
- [ ] `devtools::install()`
- [ ] `devtools::check_built()`
- ...?

### "Programmatic Commits" (for lack of a better term)

- [ ] `devtools::document()` #102  (being able to commit *without* roxygen build artefacts is a long-running pet peeve of myself)
- [ ] `styler::style_pkg()` #103
- [ ] run clang-format  #104
- ...

These are, potentially, the most destructive / confusing, because they cause programmatic diffs.
But they can also save a lot of time and enforce strong quality control; probably most valuable for the tidyverse/r-hub teams (the focus here), not many other pkg devs.


### Programmatic Code Review

- [ ] `goodpractice::goodpractice()` #105
- [ ] `lintr::lint_package()` #90
- [ ] `covr::codecov()` send results to codecov or (may need modifications to covr) #107
- [ ] run r-hub and retrieve results #71 
- ...

These are all essentially code review bots who write below commits and PRs via the github API.
They might be pretty cool and are something that might be uniquely easy to accomplish with github actions as opposed to other CI/CD.


### Continuous Delivery (deploying artefacts somewhere)

- [ ] `pkgdown::build_site()`
  - [x] deploy to gh-pages #77 #16 (this already exists in another action of mine)
  - [x] deploy to netlify (seems to have fans)
  - [x] deploy to rsync (made this for another project, probably irrelevant here)
  - [x] deploy to firebase (same)
- [ ] make a github release #108
- [ ] deploy to cran #109
- ...

**Comment by maxheld83** [comment]
structure and ideas in here are well documented in issues and labels.
